sudo: false
dist: trusty
language: node_js
os:
  - linux
node_js:
  - 7
addons:
  apt:
    packages:
    - hunspell
    - hunspell-en-us
branches:
  only:
  - master
before_install:
  - pip3 install requests
  - pip install --upgrade --user awscli
  - bundle install
script:
  - make test
after_success:
  - npm install -g surge
  - chmod ugo+x ./deploy.py
  - ./deploy.py || exit 1
