sudo: false
dist: trusty
language: node_js
os:
  - linux
node_js:
  - 7
branches:
  only:
  - master
before_install:
  - pip3 install requests
  - pip install --upgrade --user awscli
  - sudo apt-get -qq update
  - sudo apt-get install -y hunspell hunspell-en-us
  - bundle install
script:
  - make test && make
after_success:
  - npm install -g surge
  - chmod ugo+x ./deploy.py
  - ./deploy.py || exit 1
