sudo: false
dist: trusty
language: node_js
os:
  - linux
node_js:
  - 7
addons:
  apt:
    packages:
    - hunspell
    - python3-pip
branches:
  only:
  - master
before_install:
  - pip3 install requests
  - pip install --upgrade --user awscli
  - bundle install
  - cpan App::cpanminus
  - cpanm Image::TIFF
script:
  - make test
after_success:
  - node ./docsRewritesToStubs.js . || exit 1
  - npm install -g surge
  - chmod ugo+x ./deploy.py
  - ./deploy.py || exit 1
